FROM python:3.11-slim

WORKDIR /app

# Copy requirements from the local directory directly into the container's working directory
COPY requirements.txt ./requirements.txt

# Run pip install and force it to upgrade pip to ensure clean installs
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the app folder into the container
COPY app/ ./app/

EXPOSE 8001

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]